import '../imports/startup/client/schema'
import '../imports/startup/client/bootstrap'
import '../imports/startup/client/fontawesome'
import '../imports/startup/client/routes'
import '../imports/startup/client/routeHelpers'
import './main.html'
