import '../imports/startup/server/collection2'
import '../imports/startup/server/settings'
import '../imports/startup/server/csp'
import '../imports/startup/server/validation'
import '../imports/startup/server/backendConfig'
import '../imports/startup/server/error'
import '../imports/startup/server/accounts'
import '../imports/startup/server/legal'
import '../imports/startup/server/logos'
import '../imports/startup/server/testcycle'
import '../imports/startup/server/unitSet'
import '../imports/startup/server/unit'
import '../imports/startup/server/feedback'
import '../imports/startup/server/videos'
import '../imports/startup/server/content'
import '../imports/startup/server/Response'
import '../imports/startup/server/Session'
import '../imports/startup/server/diagnostics'
import '../imports/startup/server/rateLimit'
import '../imports/startup/server/sanityCheck'
import '../imports/startup/server/fixtures'

// apply patches at the very last stage
import '../imports/startup/server/patches'
